// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package handlers

import (
	"github.com/google/wire"
	"github.com/phraulino/cinetuber/pkgs/pagamentos/adapters"
	"github.com/phraulino/cinetuber/pkgs/pagamentos/core"
	"github.com/phraulino/cinetuber/pkgs/pagamentos/usecases"
)

// Injectors from pagamento_handler_wire.go:

func InitializeHandler() *PagamentoHandler {
	repoPagamento := adapters.NewRepoPagamento()
	pagamentoUseCase := usecases.NewPagamentoUseCase(repoPagamento)
	pagamentoHandler := NewPagamentoHandler(pagamentoUseCase)
	return pagamentoHandler
}

// pagamento_handler_wire.go:

var PagamentoSet = wire.NewSet(adapters.NewRepoPagamento, wire.Bind(new(core.RepoPagamento), new(*adapters.RepoPagamento)), usecases.NewPagamentoUseCase)
