// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package handlers

import (
	"database/sql"
	"github.com/google/wire"
	"github.com/phraulino/cinetuber/pkgs/pedidos/adapters"
	"github.com/phraulino/cinetuber/pkgs/pedidos/core"
	"github.com/phraulino/cinetuber/pkgs/pedidos/usecases"
)

// Injectors from pedidos_handler_wire.go:

func InitializeHandler(db *sql.DB) *PedidosHandler {
	sqlLiteRepoPedidos := adapters.NewSQLLiteRepoPedidos(db)
	consultaPedidoUseCase := usecases.NewConsultaPedidoUseCase(sqlLiteRepoPedidos)
	criaPedidoUseCase := usecases.NewCriaPedidoUseCase(sqlLiteRepoPedidos)
	adicionaItemPedidoUseCase := usecases.NewAdicionaItemPedidoUseCase(sqlLiteRepoPedidos)
	pedidosHandler := NewPedidosHandler(consultaPedidoUseCase, criaPedidoUseCase, adicionaItemPedidoUseCase)
	return pedidosHandler
}

// pedidos_handler_wire.go:

var PedidosSet = wire.NewSet(adapters.NewSQLLiteRepoPedidos, wire.Bind(new(core.RepoPedidos), new(*adapters.SQLLiteRepoPedidos)), usecases.NewCriaPedidoUseCase, usecases.NewConsultaPedidoUseCase, usecases.NewAdicionaItemPedidoUseCase)
