// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package handlers

import (
	"database/sql"
	"github.com/google/wire"
	"github.com/phraulino/cinetuber/pkgs/produtos/adapters"
	"github.com/phraulino/cinetuber/pkgs/produtos/core"
	"github.com/phraulino/cinetuber/pkgs/produtos/usecases"
)

// Injectors from produtos_handler_wire.go:

func InitializeProdutosHandler(db *sql.DB) *ProdutosHandler {
	sqlLiteRepoProdutos := adapters.NewSQLLiteRepoProdutos(db)
	listaCombosUseCase := usecases.NewListaCombosUseCase(sqlLiteRepoProdutos)
	listaProdutosUseCase := usecases.NewListaProdutosUseCase(sqlLiteRepoProdutos)
	listaProdutosPorComboUseCase := usecases.NewListaProdutosPorComboUseCase(sqlLiteRepoProdutos)
	produtosHandler := NewProdutosHandler(listaCombosUseCase, listaProdutosUseCase, listaProdutosPorComboUseCase)
	return produtosHandler
}

// produtos_handler_wire.go:

var ProdutosSet = wire.NewSet(adapters.NewSQLLiteRepoProdutos, wire.Bind(new(core.RepoProdutos), new(*adapters.SQLLiteRepoProdutos)), usecases.NewListaCombosUseCase, usecases.NewListaProdutosUseCase, usecases.NewListaProdutosPorComboUseCase)
