// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: sessoes.sql

package repositories

import (
	"context"
)

const listaSessoes = `-- name: ListaSessoes :many
SELECT
    id, filme_id, sala_id, data_horario, data_criacao, ultima_atualizacao
FROM
    "sessoes"
`

func (q *Queries) ListaSessoes(ctx context.Context) ([]Sesso, error) {
	rows, err := q.db.QueryContext(ctx, listaSessoes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Sesso
	for rows.Next() {
		var i Sesso
		if err := rows.Scan(
			&i.ID,
			&i.FilmeID,
			&i.SalaID,
			&i.DataHorario,
			&i.DataCriacao,
			&i.UltimaAtualizacao,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
