// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: filmes.sql

package repositorios

import (
	"context"
)

const listaFilmes = `-- name: ListaFilmes :many
SELECT
    id, nome, lancamento, classificacao, descricao, trailer, capa, data_criacao, ultima_atualizacao
FROM
    "filmes"
`

func (q *Queries) ListaFilmes(ctx context.Context) ([]Filme, error) {
	rows, err := q.db.QueryContext(ctx, listaFilmes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Filme
	for rows.Next() {
		var i Filme
		if err := rows.Scan(
			&i.ID,
			&i.Nome,
			&i.Lancamento,
			&i.Classificacao,
			&i.Descricao,
			&i.Trailer,
			&i.Capa,
			&i.DataCriacao,
			&i.UltimaAtualizacao,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
