// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repositorios

import (
	"database/sql"
	"time"
)

type Assento struct {
	ID                string
	Numero            int64
	Fileria           string
	SalaID            string
	DataCriacao       time.Time
	UltimaAtualizacao time.Time
}

type Cinema struct {
	ID                string
	Nome              string
	Localizacao       string
	DataCriacao       time.Time
	UltimaAtualizacao time.Time
}

type Combo struct {
	ID                string
	Nome              string
	Descricao         string
	Valor             float64
	DataCriacao       time.Time
	UltimaAtualizacao time.Time
}

type CombosProduto struct {
	ComboID           string
	ProdutoID         string
	DataCriacao       time.Time
	UltimaAtualizacao time.Time
}

type Filme struct {
	ID                string
	Nome              string
	Lancamento        time.Time
	Classificacao     string
	Descricao         string
	Trailer           string
	Capa              string
	DataCriacao       time.Time
	UltimaAtualizacao time.Time
}

type Ingresso struct {
	ID                string
	SessaoID          string
	AssentoID         string
	UsuarioID         string
	Status            string
	Valor             float64
	DataCriacao       time.Time
	UltimaAtualizacao time.Time
}

type Pedido struct {
	ID                string
	UsuarioID         string
	Status            string
	DataCriacao       time.Time
	UltimaAtualizacao time.Time
}

type PedidosIngresso struct {
	PedidoID          string
	IngressoID        string
	DataCriacao       time.Time
	UltimaAtualizacao time.Time
}

type PedidosProduto struct {
	PedidoID          string
	ProdutoID         sql.NullString
	ComboID           sql.NullString
	Nome              string
	Descricao         string
	Quantidade        float64
	Total             float64
	Tipo              string
	DataCriacao       time.Time
	UltimaAtualizacao time.Time
}

type Produto struct {
	ID                string
	Nome              string
	Descricao         string
	Valor             float64
	DataCriacao       time.Time
	UltimaAtualizacao time.Time
}

type Sala struct {
	ID                string
	Numero            int64
	CinemaID          string
	DataCriacao       time.Time
	UltimaAtualizacao time.Time
}

type Sesso struct {
	ID                string
	FilmeID           string
	SalaID            string
	DataHorario       time.Time
	DataCriacao       time.Time
	UltimaAtualizacao time.Time
}

type Usuario struct {
	ID                string
	Email             string
	DataNascimento    time.Time
	DataCriacao       time.Time
	UltimaAtualizacao time.Time
}

type ValorIngresso struct {
	ID                string
	Valor             float64
	Tipo              string
	DataCriacao       time.Time
	UltimaAtualizacao time.Time
}
