// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: valor_ingressos.sql

package repositorios

import (
	"context"
)

const consultaValorIngresso = `-- name: ConsultaValorIngresso :one
SELECT
    id, valor, tipo, data_criacao, ultima_atualizacao
FROM
    "valor_ingresso"
WHERE
    "tipo" = ?
LIMIT
    1
`

func (q *Queries) ConsultaValorIngresso(ctx context.Context, tipo string) (ValorIngresso, error) {
	row := q.db.QueryRowContext(ctx, consultaValorIngresso, tipo)
	var i ValorIngresso
	err := row.Scan(
		&i.ID,
		&i.Valor,
		&i.Tipo,
		&i.DataCriacao,
		&i.UltimaAtualizacao,
	)
	return i, err
}
