// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package handlers

import (
	"database/sql"
	"github.com/google/wire"
	adapters2 "github.com/phraulino/cinetuber/pkgs/ingressos/adapters"
	core2 "github.com/phraulino/cinetuber/pkgs/ingressos/core"
	usecases2 "github.com/phraulino/cinetuber/pkgs/ingressos/usecases"
	"github.com/phraulino/cinetuber/pkgs/pedidos/adapters"
	"github.com/phraulino/cinetuber/pkgs/pedidos/core"
	"github.com/phraulino/cinetuber/pkgs/pedidos/usecases"
)

// Injectors from pedidos_handler_wire.go:

func InitializeHandler(db *sql.DB) *PedidosHandler {
	sqlLiteRepoPedidos := adapters.NewSQLLiteRepoPedidos(db)
	consultaPedidoUseCase := usecases.NewConsultaPedidoUseCase(sqlLiteRepoPedidos)
	listaPedidosUseCase := usecases.NewListaPedidosUseCase(sqlLiteRepoPedidos)
	sqlLiteRepoIngressos := adapters2.NewSQLLiteRepoIngresso(db)
	atualizaIngressoUseCase := usecases2.NewAtualizaIngressoUseCase(sqlLiteRepoIngressos)
	checkoutPedidoUseCase := usecases.NewCheckoutPedidoUseCase(sqlLiteRepoPedidos, atualizaIngressoUseCase)
	criaPedidoUseCase := usecases.NewCriaPedidoUseCase(sqlLiteRepoPedidos)
	adicionaItemPedidoUseCase := usecases.NewAdicionaItemPedidoUseCase(sqlLiteRepoPedidos)
	pedidosHandler := NewPedidosHandler(consultaPedidoUseCase, listaPedidosUseCase, checkoutPedidoUseCase, criaPedidoUseCase, adicionaItemPedidoUseCase)
	return pedidosHandler
}

// pedidos_handler_wire.go:

var PedidosSet = wire.NewSet(adapters.NewSQLLiteRepoPedidos, adapters2.NewSQLLiteRepoIngresso, wire.Bind(new(core.RepoPedidos), new(*adapters.SQLLiteRepoPedidos)), wire.Bind(new(core2.RepoIngresso), new(*adapters2.SQLLiteRepoIngressos)), usecases.NewCriaPedidoUseCase, usecases.NewListaPedidosUseCase, usecases.NewConsultaPedidoUseCase, usecases.NewAdicionaItemPedidoUseCase, usecases.NewCheckoutPedidoUseCase, usecases2.NewAtualizaIngressoUseCase)
