// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package handlers

import (
	"database/sql"
	"github.com/google/wire"
	"github.com/phraulino/cinetuber/pkgs/filmes/core"
	"github.com/phraulino/cinetuber/pkgs/filmes/usecases"
	"github.com/phraulino/cinetuber/shared/adapters/sqlite"
)

// Injectors from filmes_handler_wire.go:

func InitializeFilmesHandler(db *sql.DB) *FilmesHandler {
	sqlLiteRepoFilmes := adapters.NewSQLLiteRepoFilmes(db)
	listarFilmesUseCase := usecases.NewListarFilmesUseCase(sqlLiteRepoFilmes)
	filmesHandler := NewFilmesHandler(listarFilmesUseCase)
	return filmesHandler
}

// filmes_handler_wire.go:

var filmesSet = wire.NewSet(adapters.NewSQLLiteRepoFilmes, wire.Bind(new(core.RepoFilmes), new(*adapters.SQLLiteRepoFilmes)), usecases.NewListarFilmesUseCase)
