// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package handlers

import (
	"database/sql"
	"github.com/google/wire"
	adapters2 "github.com/phraulino/cinetuber/pkgs/ingressos/adapters"
	core2 "github.com/phraulino/cinetuber/pkgs/ingressos/core"
	usecases2 "github.com/phraulino/cinetuber/pkgs/ingressos/usecases"
	adapters3 "github.com/phraulino/cinetuber/pkgs/pedidos/adapters"
	core3 "github.com/phraulino/cinetuber/pkgs/pedidos/core"
	usecases3 "github.com/phraulino/cinetuber/pkgs/pedidos/usecases"
	"github.com/phraulino/cinetuber/pkgs/usuarios/adapters"
	"github.com/phraulino/cinetuber/pkgs/usuarios/core"
	"github.com/phraulino/cinetuber/pkgs/usuarios/usecases"
)

// Injectors from usuarios_handler_wire.go:

func InitializeHandler(db *sql.DB) *UsuariosHandler {
	sqlLiteRepoUsuarios := adapters.NewSQLLiteRepoUsuarios(db)
	criaUsuarioUseCase := usecases.NewCriaUsuarioUseCase(sqlLiteRepoUsuarios)
	geraTokenUsuarioUseCase := usecases.NewGeraTokenUsuarioUseCase(sqlLiteRepoUsuarios)
	listaUsuariosUseCase := usecases.NewListaUsuariosUseCase(sqlLiteRepoUsuarios)
	sqlLiteRepoIngressos := adapters2.NewSQLLiteRepoIngresso(db)
	buscaIngressoUseCase := usecases2.NewBuscaIngressoUseCase(sqlLiteRepoIngressos)
	listaIngressosUsuarioUseCase := usecases.NewListaIngressosUsuarioUseCase(sqlLiteRepoUsuarios, buscaIngressoUseCase)
	sqlLiteRepoPedidos := adapters3.NewSQLLiteRepoPedidos(db)
	listaPedidosUseCase := usecases3.NewListaPedidosUseCase(sqlLiteRepoPedidos)
	listaPedidosUsuarioUseCase := usecases.NewListaPedidosUsuarioUseCase(sqlLiteRepoUsuarios, listaPedidosUseCase)
	buscaUsuarioUseCase := usecases.NewBuscaUsuarioUseCase(sqlLiteRepoUsuarios)
	usuariosHandler := NewUsuariosHandler(criaUsuarioUseCase, geraTokenUsuarioUseCase, listaUsuariosUseCase, listaIngressosUsuarioUseCase, listaPedidosUsuarioUseCase, buscaUsuarioUseCase)
	return usuariosHandler
}

// usuarios_handler_wire.go:

var UsuariosSet = wire.NewSet(wire.Bind(new(core.RepoUsuarios), new(*adapters.SQLLiteRepoUsuarios)), wire.Bind(new(core2.RepoIngresso), new(*adapters2.SQLLiteRepoIngressos)), wire.Bind(new(core3.RepoPedidos), new(*adapters3.SQLLiteRepoPedidos)), adapters.NewSQLLiteRepoUsuarios, adapters3.NewSQLLiteRepoPedidos, adapters2.NewSQLLiteRepoIngresso, usecases.NewCriaUsuarioUseCase, usecases.NewListaUsuariosUseCase, usecases.NewBuscaUsuarioUseCase, usecases.NewGeraTokenUsuarioUseCase, usecases.NewListaIngressosUsuarioUseCase, usecases.NewListaPedidosUsuarioUseCase, usecases3.NewListaPedidosUseCase, usecases2.NewBuscaIngressoUseCase)
