// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package handlers

import (
	"database/sql"
	"github.com/google/wire"
	"github.com/phraulino/cinetuber/pkgs/ingressos/adapters"
	"github.com/phraulino/cinetuber/pkgs/ingressos/core"
	"github.com/phraulino/cinetuber/pkgs/ingressos/usecases"
)

// Injectors from valor_ingresso_handler_wire.go:

func InitializeHandler(db *sql.DB) *IngressoHandler {
	sqlLiteRepoIngressos := adapters.NewSQLLiteRepoIngresso(db)
	consultaValorIngressoUseCase := usecases.NewConsultaValorIngressoUseCase(sqlLiteRepoIngressos)
	ingressoHandler := NewIngressoHandler(consultaValorIngressoUseCase)
	return ingressoHandler
}

// valor_ingresso_handler_wire.go:

var valorIngressoSet = wire.NewSet(adapters.NewSQLLiteRepoIngresso, wire.Bind(new(core.RepoIngresso), new(*adapters.SQLLiteRepoIngressos)), usecases.NewConsultaValorIngressoUseCase)
