// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package handlers

import (
	"database/sql"
	"github.com/google/wire"
	"github.com/phraulino/cinetuber/pkgs/ingressos/adapters"
	"github.com/phraulino/cinetuber/pkgs/ingressos/core"
	"github.com/phraulino/cinetuber/pkgs/ingressos/usecases"
)

// Injectors from valor_ingresso_handler_wire.go:

func InitializeConsultaValorIngressoHandler(db *sql.DB) *ConsultaValorIngressoHandler {
	sqlLiteRepoValorIngresso := adapters.NewSQLLiteRepoValorIngresso(db)
	consultaValorIngressoUseCase := usecases.NewConsultaValorIngressoUseCase(sqlLiteRepoValorIngresso)
	consultaValorIngressoHandler := NewConsultaValorIngressoHandler(consultaValorIngressoUseCase)
	return consultaValorIngressoHandler
}

// valor_ingresso_handler_wire.go:

var valorIngressoSet = wire.NewSet(adapters.NewSQLLiteRepoValorIngresso, wire.Bind(new(core.RepoValorIngresso), new(*adapters.SQLLiteRepoValorIngresso)), usecases.NewConsultaValorIngressoUseCase)
