// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repositories

import (
	"database/sql"
)

type Assento struct {
	ID                string
	Numero            sql.NullInt64
	Fileria           sql.NullString
	SalaID            sql.NullString
	UltimaAtualizacao sql.NullTime
}

type Cinema struct {
	ID                string
	Nome              sql.NullString
	Localizacao       sql.NullString
	UltimaAtualizacao sql.NullTime
}

type Combo struct {
	ID                 string
	Nome               sql.NullString
	Descricao          sql.NullString
	Valor              sql.NullFloat64
	ChaveClassificacao sql.NullString
	UltimaAtualizacao  sql.NullTime
}

type CombosProduto struct {
	ComboID           sql.NullString
	ProdutoID         sql.NullString
	UltimaAtualizacao sql.NullTime
}

type Filme struct {
	ID                 string
	Nome               sql.NullString
	DataLancamento     sql.NullTime
	Classificacao      sql.NullString
	Descricao          sql.NullString
	Trailer            sql.NullString
	Capa               sql.NullString
	ExpectativaPublico sql.NullInt64
	UltimaAtualizacao  sql.NullTime
}

type Ingresso struct {
	ID                string
	SessaoID          sql.NullString
	AssentoID         sql.NullString
	UsuarioID         sql.NullString
	Status            sql.NullString
	Valor             sql.NullFloat64
	UltimaAtualizacao sql.NullTime
}

type Pedido struct {
	ID                string
	UsuarioID         sql.NullString
	Data              sql.NullTime
	ValorTotal        sql.NullFloat64
	Status            sql.NullString
	UltimaAtualizacao sql.NullTime
}

type PedidosCombo struct {
	PedidoID           sql.NullString
	ComboID            sql.NullString
	ChaveClassificacao sql.NullString
	UltimaAtualizacao  sql.NullTime
}

type PedidosIngresso struct {
	PedidoID          sql.NullString
	IngressoID        sql.NullString
	UltimaAtualizacao sql.NullTime
}

type PedidosProduto struct {
	PedidoID          sql.NullString
	ProdutoID         sql.NullString
	UltimaAtualizacao sql.NullTime
}

type Produto struct {
	ID                string
	Nome              sql.NullString
	Descricao         sql.NullString
	Valor             sql.NullFloat64
	UltimaAtualizacao sql.NullTime
}

type Sala struct {
	ID                string
	Numero            sql.NullInt64
	CinemaID          sql.NullString
	UltimaAtualizacao sql.NullTime
}

type Sesso struct {
	ID                string
	FilmeID           sql.NullString
	SalaID            sql.NullString
	DataHorario       sql.NullTime
	UltimaAtualizacao sql.NullTime
}

type Usuario struct {
	ID                string
	Email             sql.NullString
	DataNascimento    sql.NullTime
	UltimaAtualizacao sql.NullTime
}
